suffolk-northern/main

train_model/TrainModel.java, train_model/communication/ControllerLink.java, train_model/subsystem_demo/UI.java
Addresses issues I discussed with @crlsvzqz5 privately.
- Power input exception behavior is documented
- Realistic mass, engine power, and braking force
=> Train model realism

integration/Main.java
Uncomments `TrackModel` instantiation in `integration/Main.java`.
Linking/interfaces between modules still needs to be done.
=> Integration

integration/Main.java, mbo/MBO.java, patrick/Patrick.java, spongebob/Spongebob.java, test/TestTrain.java, test/TestyTest.java, test/updater/TestClock.java, test/updater/TestTimingRobustness.java, test/updater/mock/NaughtyModule.java, test/updater/mock/NiceModule.java, test/updater/mock/NoisyModule.java, test/updater/mock/TimeModule.java, track_controller/TrackController.java, train_model/TrainModel.java, train_model/subsystem_demo/Main.java, train_model/subsystem_demo/mbo/MBO.java, train_model/subsystem_demo/track_model/TrackModel.java, train_model/subsystem_demo/train_controller/Controller.java, updater/Clock.java, updater/ClockMultiplier.java, updater/Updateable.java, updater/Updater.java
- robust/tested fixed-frequency Updater timing, ready for simulation with speedups
- frequency multiplier for modules that need faster updates than others
- simulation clock for any module that needs one
=> Updater timing

README.md
Documents where to get SQL library from.
=> README Dependencies

integration/Main.java, train_controller/TrainController.java
Uncommented TrainController sections in integration/Main.java
=> TrainController integration

Jenkinsfile
=> Continuous integration

integration/Main.java, train_model/PointMass.java, train_model/TrainModel.java, train_model/subsystem_demo/UI.java
Initial functionality: trains run on the track.
Does not observe switch states.
=> Steer trains

ctc/Ctc.java
Switches should handle multiple trains, train location takes into account more possibilities plus broken blocks
=> Improved switch and train movement behavior

track_model/Station.java, track_model/TestFrame.form, track_model/TestFrame.java, track_model/TrackBlock.java, track_model/TrackModel.java, track_model/TrackModelFrame.java, track_model/TrackModelMapPanel.java, track_model/tables/BlockTable.java, track_model/tables/CrossingTable.java, track_model/tables/StationTable.java, track_model/tables/SwitchTable.java, track_model/tables/TrackModelTable.java, track_model/tables/TrackModelTableModel.java
Heaters and switches and tabs, oh my
=> Roger station dev

ctc/Ctc.java
Any remaining funny business with switches is on Roger's end in the database itself
=> Fixed checking for switch states at start

track_model/TrackModelFrame.java, track_model/tables/BlockTable.java, track_model/tables/CrossingTable.java, track_model/tables/StationTable.java, track_model/tables/SwitchTable.java
Squelches some errors, some semi-important GUI tweakz
=> Roger table errors

track_model/TrackModel.java, track_model/TrackModelMapPanel.java
=> Temperature and heater

track_model/MurphFrame.java, track_model/TrackModel.java
=> Minor murphy behavior tweaks

ctc/CtcUI.form, ctc/CtcUI.java, integration/UI.form, integration/UI.java, mbo/MboControllerUI.java, mbo/MboSchedulerUI.java, train_controller/TrainControllerUI.java
=> More window fixes

train_model/Cabin.java, train_model/Failure.java, train_model/TrainModel.java, train_model/communication/Relay.java, train_model/subsystem_demo/UI.form, train_model/subsystem_demo/UI.java
Does not change any interfaces. Does not directly affect any other module.
- failures
- UI format fixes
- heading replaced with 0 grade
- ID
=> Train model independent features

train_model/PointMass.java, train_model/TrainModel.java
Don't exchange passengers if not at a station.
=> Exchange passengers behavior

train_model/PointMass.java, train_model/TrainModel.java
=> Train physics

train_model/TrainModel.java, train_model/communication/ControllerLink.java, train_model/subsystem_demo/UI.form, train_model/subsystem_demo/UI.java
- Controller can read engine and brake states to identify failures
- Emergency brake can be released
- Model can request emergency brake
- Controller can display advertisements
Also:
- Model GUI refresh rate decreased
=> Train model and train controller interface

ctc/Ctc.java, ctc/CtcUI.java
UI still has a bit of a problem with spacing, but it's mostly good
=> Manually flip switch

train_controller/TrainController.java
temp set between +-1 of setpoint
=> Heaterperfectionism

train_controller/TrainController.java, train_controller/TrainControllerUI.java
minor fixes
- gui has title
- rid of unused vars
=> Controllerfixes
